- name: Download GitLab Runner repository script
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/gitlab-runner-script.deb.sh
    mode: '0755'

- name: Execute GitLab Runner repository script
  command: bash /tmp/gitlab-runner-script.deb.sh

- name: Install GitLab Runner
  apt:
    name: gitlab-runner

- name: Add gitlab-runner user to docker group
  user:
    name: gitlab-runner
    groups: docker
    append: true
