namespace: wolkenarchitekt
name: base
version: 1.0.0
readme: README.md
authors:
- Ingo Weinmann <mail@ingoweinmann.de>
description: Ansible roles
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: http://github.com/wolkenarchitekt/ansible_collections
#documentation: http://docs.example.com
#homepage: http://example.com
#issues: http://example.com/issue/tracker
build_ignore: []
