---
namespace: wolkenarchitekt
name: base
version: 1.0.0
readme: README.md
authors:
- Ingo Weinmann <mail@ingoweinmann.de>
description: Ansible base collection
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: http://github.com/wolkenarchitekt/ansible-collection-base
build_ignore: []
