---
galaxy_info:
  author: mail@ingoweinmann.de
  description: Installs Docker engine
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
