- name: 'Install python and pyenv'
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-pipx
      - pyenv
      - tk
      - uv
  become: true

- name: 'Install ipython'
  ansible.builtin.command: pipx install ipython

- name: 'Install Python versions'
  include_tasks: python-pyenv-install.yml
  loop:
    - { version: '3.9.18' }
    - { version: '3.10.13' }
    - { version: '3.11.3' }
    - { version: '3.11.7' }
    - { version: '3.11.9' }
    - { version: '3.12.1' }
    - { version: '3.12.2' }
  loop_control:
    loop_var: python
