- name: 'Install Python Debian packages'
  apt:
    pkg:
      - python3-pip
      - python3-venv
      - pipx
  become: true

- name: 'Setup ipython'
  import_tasks: ipython.yml

- name: 'Install utils'
  community.general.pipx:
    name: '{{ item }}'
  loop:
    - ruff
    - black
    - autoflake
    - isort

