- import_tasks: main-debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: main-archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: 'Setup ipython'
  import_tasks: ipython.yml

- name: 'Install utils'
  community.general.pipx:
    name: '{{ item }}'
  loop:
    - ruff
    - black
    - autoflake
    - isort

