- name: 'Create docker config dir'
  file:
    path: '/home/{{ ansible_user }}/.docker'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  become: true
  become_user: '{{ ansible_user }}'

- name: 'Configure Docker to use proxy (needed for building Docker images)'
  ansible.builtin.copy:
    src: files/config.json
    dest: '/home/{{ ansible_user }}/.docker/config.json'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0600
  become: true

- name: 'Check if docker-service exists'
  stat:
    path: /usr/lib/systemd/system/docker.service
  register: docker_service

- name: 'Configure Docker service to use proxy (passed as environment to Docker services)'
  ansible.builtin.blockinfile:
    path: /usr/lib/systemd/system/docker.service
    insertafter: 'Restart=always'
    block: |
      Environment="HTTP_PROXY=http://proxy.th-wildau.de:8080"
      Environment="HTTPS_PROXY=http://proxy.th-wildau.de:8080"
  become: true
  notify:
    - 'Restart docker'
  when: docker_service.stat.exists
