- import_tasks: main-debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: main-archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: 'Set Chrome executable'
  ansible.builtin.lineinfile:
    path: '/etc/environment'
    line: export CHROME_EXECUTABLE=/usr/bin/chromium-browser
  become: true
