- name: Install Docker dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
  become: true

- name: 'Add user to docker group'
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true
  become: true
  notify:
    - 'Restart Docker'
  register: docker_group_added

- name: 'Reboot if required'
  reboot:
  become: true
  when: docker_group_added.changed and ansible_connection != "local"

- name: 'Check if Docker is running'
  systemd:
    name: docker
    state: started
  register: service_status
  ignore_errors: yes

- name: 'Restart Docker'
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: docker
    enabled: true
  become: true
  when: service_status.failed
