- name: 'Get DEB architecture'
  ansible.builtin.command: dpkg --print-architecture  # noqa no-changed-when
  register: deb_architecture

#- name: 'Copy sdkmanager'
#  ansible.builtin.copy:
#    src: 'files/sdkmanager_2.2.0-12021_{{ deb_architecture.stdout }}.deb'
#    dest: '/tmp/sdkmanager_2.2.0-12021_{{ deb_architecture.stdout }}.deb'
#    mode: 0644
#    backup: true
#  ignore_errors: true
#  register: sdkmanager_copy
#
#- name: 'Download SDKManager'
#  get_url:
#    url: 'https://developer.download.nvidia.com/sdkmanager/secure/clients/sdkmanager-2.2.0.12021/sdkmanager_2.2.0-12021_{{ deb_architecture.stdout }}.deb'
#    dest: '/tmp/sdkmanager_2.2.0-12021_{{ deb_architecture.stdout }}.deb'
#  when: sdkmanager_copy.failed

#- name: 'Install SDKManager'
#  apt:
#    deb: '/tmp/sdkmanager_2.2.0-12021_{{ deb_architecture.stdout }}.deb'


- name: 'Download CUDA keyring'
  get_url:
    url: 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb'
    dest: '/tmp/cuda-keyring_1.1-1_all.deb'

- name: 'Install CUDA keyring'
  apt:
    deb: '/tmp/cuda-keyring_1.1-1_all.deb'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
  become: true

- name: 'Install SDKManager'
  apt: pkg=sdkmanager
